[build]
  command = "npm run netlify-build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Cache static assets and set proper MIME types
[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

[[headers]]
  for = "/_next/static/chunks/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"
    
[[headers]]
  for = "/_next/static/media/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff2"
    
[[headers]]
  for = "/_next/static/media/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Favicon and icon files
[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "image/x-icon"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Single page application handling - improved for Next.js static export
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  
# Handle 404 errors properly
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = false

# Set up catch-all for any other asset types
[[headers]]
  for = "/_next/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
